# mysql
mysql:
  database_url: "mysql+aiomysql://root:password@localhost:3306/news_db_dev"
# 日志
logging:
  level: "INFO"
# 钉钉
dingtalk:
  enabled: true
  webhook_url: "https://oapi.dingtalk.com/robot/send?access_token=dev_token"
  secret: "dev_secret"